name: ci

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.0
      - uses: Swatinem/rust-cache@v2
      - name: msrv
        run: cargo check --workspace --all-targets --all-features --locked

  test:
    runs-on: ubuntu-latest
    needs: msrv
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: install cargo-audit
        run: cargo install cargo-audit --locked
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: audit
        run: cargo audit
      - name: examples
        run: cargo check --workspace --examples
      - name: test
        run: cargo test --workspace --all-targets
